name: TDLib CI

on:
  push:
    branches: [ master ]

jobs:
  TDLib:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build TDLib
      run: docker run debian:buster -t .:/td bash /td/build.sh