name: TDLib CI

on:
  push:
    branches: [ master ]

jobs:
  linux64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build TDLib
        run: docker run -v $PWD:/td debian:buster bash /td/build.sh
      - uses: actions/upload-artifact@master
        name: Upload TDJni Library
        with:
          name: libtdjni.so
          path: libtdjni.so
  win64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.6'
          architecture: x64
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Install gperf
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install gperf
      - name: Setup vcpkg
        run: |
          git submodule add https://github.com/Microsoft/vcpkg.git
      - name: Cache vcpkg's artifacts
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/vcpkg/
          key: ${{ hashFiles('.git/modules/vcpkg/HEAD') }}-${{ runner.os }}
      - name: Run vcpkg
        uses: lukka/run-vcpkg@v0
        with:
          vcpkgArguments: 'openssl:x64-windows zlib:x64-windows'
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
      - name: Build TDLib
        shell: bash
        run: |
          git submodule init
          git submodule update
          cd td
          rm -rf build
          mkdir build
          cd build
          cmake -A x64 -DCMAKE_INSTALL_PREFIX:PATH=.. -DTD_ENABLE_JNI=ON -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../../vcpkg/scripts/buildsystems/vcpkg.cmake ..
          cmake --build . --target install --config Release
          cd ../..
          rm -rf build
          mkdir build
          cd build
          cmake -A x64 -DCMAKE_INSTALL_PREFIX:PATH=../td/tdlib -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../vcpkg/scripts/buildsystems/vcpkg.cmake -DTd_DIR:PATH=$(Resolve-Path ../td/lib/cmake/Td) ..
          cmake --build . --target install --config Release
          mv libtdjni.so ..
      - uses: actions/upload-artifact@master
        name: Upload TDJni Library
        with:
          name: tdjni.dll
          path: tdjni.dll